use { arguments, shape, error } from common

record argument-metadata {
    name: string,
    description: option<string>,
    default-value: option<string>,
}

record model-metadata {
    name: string,
    description: option<string>,
    arguments: list<argument-metadata>,
}

resource model {
    metadata: func() -> model-metadata
    shape: func(args: arguments) -> expected<shape, error>
}

record plugin-metadata {
    name: string,
    version: string,
    short-description: option<string>,
    description: option<string>,
    homepage: option<string>,
    repository: option<string>,
    license: option<string>,
}

resource plugin {
    metadata: func() -> plugin-metadata
    models: func() -> list<model>
}

init: func() -> expected<plugin, error>
