/// Write something to the console *without* appending a newline.
print: func(message: string)

/// Immediately halt execution with a message.
abort: func(message: string)

record timespec {
    secs: s64,
    nanos: u32,
}

/// The amount of time that has passed since the UNIX epoch (UTC).
time: func() -> timespec
